version: "2.18.1"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=shortcut
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    restart: always
  url_shortcut:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JDBC_URL=jdbc:postgresql://db:5433/shortcut
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=password
      - JDBC_DRIVER=org.postgresql.Driver
    ports:
      - "127.0.0.1:8080:8080"
    container_name: url_shortcut
    depends_on:
      - db